# Generated by Django 4.0.5 on 2022-07-01 16:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageCollection',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified On')),
                ('is_approved', models.BooleanField(db_index=True, default=False)),
                ('title', models.CharField(max_length=300, verbose_name='Image Name')),
                ('slug', models.CharField(blank=True, db_index=True, editable=False, max_length=300, null=True)),
                ('file', models.ImageField(max_length=250, upload_to='')),
                ('size', models.PositiveIntegerField(blank=True, default=0, editable=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
