# Generated by Django 4.0.5 on 2022-07-01 16:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified On')),
                ('is_approved', models.BooleanField(db_index=True, default=False)),
                ('display_id', models.CharField(max_length=20, unique=True, verbose_name='#')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('published_time', models.PositiveIntegerField(default=0)),
                ('status', models.PositiveIntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
                ('keywords', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified On')),
                ('is_approved', models.BooleanField(db_index=True, default=False)),
                ('display_id', models.CharField(max_length=20, unique=True, verbose_name='#')),
                ('name', models.CharField(db_index=True, max_length=250, unique=True)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(blank=True, help_text='Only for SEO purpose', max_length=68, null=True)),
                ('description', models.CharField(blank=True, help_text='Only for SEO purpose', max_length=150, null=True)),
                ('keywords', models.TextField(blank=True, help_text='Only for SEO purpose', null=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
