# Generated by Django 4.0.5 on 2022-07-01 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0001_initial'),
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='article',
            name='main_poster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles_main_poster', to='storage.imagecollection'),
        ),
        migrations.AddField(
            model_name='article',
            name='related_topics',
            field=models.ManyToManyField(blank=True, related_name='related_articles', to='articles.tag'),
        ),
        migrations.AddField(
            model_name='article',
            name='small_poster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles_small_posters', to='storage.imagecollection'),
        ),
        migrations.AlterUniqueTogether(
            name='article',
            unique_together={('slug',)},
        ),
    ]
