# Generated by Django 4.0.5 on 2022-07-02 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_remove_article_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='published_time',
        ),
        migrations.AddField(
            model_name='article',
            name='published_on',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
    ]
