# Generated by Django 4.0.5 on 2022-07-03 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_article_publisher_alter_article_creator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='related_topics',
            new_name='tags',
        ),
    ]
