# Generated by Django 4.0.5 on 2022-07-05 14:59

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_rename_related_topics_article_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=django_quill.fields.QuillField(blank=True, null=True),
        ),
    ]
